## Imports

In [1]:
import os
import numpy as np
import pandas as pd

## Cargar datos

In [2]:
root = ".."
folder_raw_datasets = "datasets/raw"
data_version = "20261028"
file_calendar = "calendar.csv"
file_stores = "stores.csv"
file_transactions = "transactions.csv"

route_calendar = os.path.join(root,folder_raw_datasets,data_version,file_calendar)
route_stores = os.path.join(root,folder_raw_datasets,data_version,file_stores)
route_transactions = os.path.join(root,folder_raw_datasets,data_version,file_transactions)

calendar = pd.read_csv(route_calendar)
stores = pd.read_csv(route_stores)
transactions = pd.read_csv(route_transactions)

## Exploracion inicial y ajuste de los datos

### Calendar

In [3]:
calendar.head(3)

,date,day_of_week,day_name,week_of_year,month,year,quarter,season,is_holiday,holiday_name,is_payday,is_weekend,is_navidad_season,is_buen_fin,is_semana_santa
0,2023-01-01,6,Sunday,52,1,2023,1,Invierno,True,Año Nuevo,False,True,True,False,False
1,2023-01-02,0,Monday,1,1,2023,1,Invierno,False,NaN,False,False,True,False,False
2,2023-01-03,1,Tuesday,1,1,2023,1,Invierno,False,NaN,False,False,True,False,False

In [4]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 425 entries, 0 to 424
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               425 non-null    str
 1   day_of_week        425 non-null    int64
 2   day_name           425 non-null    str
 3   week_of_year       425 non-null    int64
 4   month              425 non-null    int64
 5   year               425 non-null    int64
 6   quarter            425 non-null    int64
 7   season             425 non-null    str
 8   is_holiday         425 non-null    bool
 9   holiday_name       18 non-null     str
 10  is_payday          425 non-null    bool
 11  is_weekend         425 non-null    bool
 12  is_navidad_season  425 non-null    bool
 13  is_buen_fin        425 non-null    bool
 14  is_semana_santa    425 non-null    bool
dtypes: bool(6), int64(5), str(4)
memory usage: 32.5 KB

In [5]:
calendar.describe()

       day_of_week  week_of_year       month         year     quarter
count   425.000000    425.000000  425.000000   425.000000  425.000000
mean      2.992941     23.496471    5.814118  2023.141176    2.296471
std       2.004111     15.917701    3.655029     0.348614    1.162143
min       0.000000      1.000000    1.000000  2023.000000    1.000000
25%       1.000000      8.000000    2.000000  2023.000000    1.000000
50%       3.000000     22.000000    6.000000  2023.000000    2.000000
75%       5.000000     37.000000    9.000000  2023.000000    3.000000
max       6.000000     52.000000   12.000000  2024.000000    4.000000

In [6]:
# date
calendar["date"] = pd.to_datetime(calendar["date"],format="%Y-%m-%d") 
# no le pongo errors="coerce" porque quiero darme cuenta si algo está mal con el formato de las fechas.

#Explorar nulos o ausentes
print(f"cantidad de datos nulos/ausentes: {calendar['date'].isnull().sum()}")

# Explorar rango de datos y ver si coincide con lo indicado en data_dictionary.md
print(f"Rango de fechas: {calendar['date'].min()} - {calendar['date'].max()}")

cantidad de datos nulos/ausentes: 0
Rango de fechas: 2023-01-01 00:00:00 - 2024-02-29 00:00:00

In [7]:
# day_of_week	
# El tipo de datos es int64; podríamos ahorrar memoria usando un tipo int8, ya que los valores de día de la semana van de 1 a 7.
calendar["day_of_week"] = calendar["day_of_week"].astype("int8")
print(f"cantidad de días contados")
print(f"{calendar['day_of_week'].value_counts()}")
print("")
print(f"cantidad de datos nulos/ausentes: {calendar['day_of_week'].isnull().sum()}")
print(f"Rango de días de la semana: {calendar['day_of_week'].min()} - {calendar['day_of_week'].max()}")

cantidad de días contados
day_of_week
6    61
0    61
1    61
2    61
3    61
4    60
5    60
Name: count, dtype: int64

cantidad de datos nulos/ausentes: 0
Rango de días de la semana: 0 - 6

In [ ]:
# day_name
calendar["day_name"].value_counts()
print(f"cantidad de datos nulos/ausentes: {calendar['day_name'].isnull().sum()}")
print(f"Dias de la semana = {calendar['day_name'].unique()}")

cantidad de datos nulos/ausentes: 0
Dias de la semana = <StringArray>
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
Length: 7, dtype: str

In [ ]:
# week_of_year
# El tipo de datos es int64; podríamos ahorrar memoria usando un tipo int8, ya que los valores de semana del año van de 1 a 52.
calendar["week_of_year"] = calendar["week_of_year"].astype("int8")
print(f"cantidad de datos nulos/ausentes: {calendar['week_of_year'].isnull().sum()}")
print(f"Rango de semanas del año: {calendar['week_of_year'].min()} - {calendar['week_of_year'].max()}")

cantidad de datos nulos/ausentes: 0
Rango de semanas del año: 1 - 52

In [ ]:
month

In [ ]:
year

In [ ]:
quarter

In [ ]:
season

In [ ]:
is_holiday

In [ ]:
holiday_name

In [ ]:
is_payday

In [ ]:
is_weekend

In [ ]:
is_navidad_season

In [ ]:
is_buen_fin

In [ ]:
is_semana_santa

### Stores

In [ ]:
stores.head(2)

In [ ]:
stores.info()

In [ ]:
stores.describe()

### Transactions

In [ ]:
transactions.head(5)

In [ ]:
transactions.info()

In [ ]:
transactions.describe()

## Preguntas básicas de interés para el negocio

### 1. ¿Cuál es la región que tiene mayor cantidad de ventas?

In [ ]:
# para resolver esto se deben unir las tablas de transacciones con la de tiendas y luego agrupar por región para sumar las ventas.
merged = transactions.merge(stores, on='store_id')
sales_by_region = merged.groupby('region')['amount_total'].sum()
sales_by_region.sort_values(ascending=False)
# La región con mayor cantidad de ventas será la primera en este listado.

### 2. ¿Cuál es la tienda con mayor cantidad de ventas por región?

### 3. ¿Qué formato de tienda tiene mejores ingresos?

### 4. ¿Cuál es la tendencia de ventas a lo largo del tiempo en cada una de las tiendas (monto total y ticket promedio)?